name: test
on:
  push:
    branches:
    - '*'

jobs:
  dune-monorepo-benchmark-runner-build:
    name: Build the benchmark runner
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get install -y build-essential opam sudo pkg-config
      - uses: actions/checkout@v3
      - name: Setup opam
        run: opam init --disable-sandboxing --auto-setup && opam switch create 4.14.1
      - name: Build the benchmark runner
        run: opam install ./dune-monorepo-benchmark-runner -y
